### ISSUE TITLE
Provide an integration with Apache Isis (or extensibility to allow such an integration to be easy to do).

### ISSUE THREAD

**Issue by danhaywood** [sculptor/sculptor#158]
Hi folks,
I'm a committer on [Apache Isis](http://isis.apache.org), a DDD framework, and one of our JIRA tickets [ISIS-369](https://issues.apache.org/jira/browse/ISIS-369?focusedCommentId=14253088&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14253088) is to build a DSL to encapsulate its [programming model](http://isis.apache.org/documentation.html).

We just had a comment on that ticket drawing our attention to your project, which looks pretty interesting, and uses the same technologies that we had in mind (XText).

Right now ISIS-369 remains far down our priority list, but you might like to consider our use cases and see if either an integration could be implemented or provide appropriate hooks into your framework such that we could support our ideas for a DSL.

**Comment by tjuerge** [comment]
I did some experiments with Xtexts support for [Java types](https://www.eclipse.org/Xtext/documentation/305_xbase.html#jvmtypes) and [expressions (Xbase)](https://www.eclipse.org/Xtext/documentation/305_xbase.html#xbase-expressions). This looks promising. A prototype is available from https://github.com/vaulttec/isis-script.

But this approach (generating Java code while modifying the model within the Eclipse editor) is not usable for Sculptor. Instead this is a specific solution for Apache Isis.

**Comment by danhaywood** [comment]
Great to see you devote some (a lot?) of time on this, much appreciated.

I have some suggestions for the DSL itself (though I think you've done a very good job already).  Shall I raise those suggestions on that new github repo?

Also (and this is very minor) ... although the committers are all long time users of Eclipse, most of us have moved to IntelliJ in the last year; one reason is it plays much better with the DataNucleus enhancer.  As I'm sure you are aware, apparently XText is being ported to IntelliJ.  Is this something that you are tracking/intend to look into yourself?

Thanks again,
Dan

**Comment by danhaywood** [comment]
fyi, I posted a link announcing this work on our mailing list, see http://isis.markmail.org/thread/czwhqaitv6gbrhzy

**Comment by tjuerge** [comment]
Hi Dan,

> I have some suggestions for the DSL itself (though I think you've done a very good job already). Shall I raise those suggestions on that new github repo?

Sure, use the other repo. So it's easier to track.

> Also (and this is very minor) ... although the committers are all long time users of Eclipse, most of us have moved to IntelliJ in the last year; one reason is it plays much better with the DataNucleus enhancer. As I'm sure you are aware, apparently XText is being ported to IntelliJ. Is this something that you are tracking/intend to look into yourself?

I'm a long-time user of (and plugin developer for) Eclipse. So no plans on switching IDE here yet :-)

Regarding the DataNucleus enhancer: An Isis Script is "compiled" to Java source code. Maybe we can provide a tighter integration of this Xtext/Xbase/Xtend code generation with the DataNucleus enhancer.

/Torsten

**Comment by tjuerge** [comment]
A formal description of the Isis Script DSL is available [here](https://github.com/vaulttec/isis-script/blob/develop/dsl.md#isis-script-dsl). The implementation of the corresponding Eclipse editor [was updated accordingly](http://vaulttec.org/2015/09/05/isis-script-updated-alpha-version.html).

**Comment by danhaywood** [comment]
Hi Torsten,

Really great stuff, this.... I'm looking forward to trying it out,
hopefully this week.

Would it be okay for me to link to all this from isis.apache.org, and
perhaps record a screencast or two about it?  I can't imagine you'll
object, but thought I should ask.

Cheers

Dan

**Comment by tavoda** [comment]
Uaaau, a lot of work Torsten. However is it somehow usable for Sculptor alone? Should this be something like GUI DSL? I see doesn't fill very well with current sculptor but can it somehow extend base model?

**Comment by tjuerge** [comment]
As ISIS-369 was closed we close this ticket as well.
