### ISSUE TITLE
Examples: Add Spring Boot sample

### ISSUE THREAD

**Issue by tjuerge** [sculptor/sculptor#167]
With [Spring Boot](http://projects.spring.io/spring-boot/) the Spring Team provides an excellent tool for boot-strapping new Spring projects in no-time - may it from within the command line, IDE or web browser. This tool helps Spring developers picking the right dependencies and configuring the application properly. It creates stand-alone Spring applications (including an optional web container) which can be executed from command line via `java -jar` or deployed as WAR.

Sculptor [REST Tutorial](http://sculptorgenerator.org/documentation/rest-tutorial) is a very good showcase demonstrating the usage of Sculptor with Spring Boot, Spring Java Config #166 and Thymeleaf HTML presentation #165.

**Comment by rmswalsh** [comment]
This suggests that the REST tutorial is a good demo of Sculptor with Spring Boot.

However having created the project from the archectype the REST project does not reference Spring Boot at all.

**Comment by tjuerge** [comment]
> However having created the project from the archectype the REST project does not reference Spring Boot at all.

Yes, that's intended (#166 and the yet to be created ticket for updating the Maven archetypes) need to be fixed first :-).

**Comment by tjuerge** [comment]
> This suggests that the REST tutorial is a good demo of Sculptor with Spring Boot.

You're right. So I changed the description as follows:

> Sculptors REST Tutorial is a very good starting point for creating a Sculptor example which uses Spring Boot, Spring Java Config #166 and Thymeleaf HTML presentation #165.
> 
> Currently there's no Sculptor Maven archetype for generating a Sculptor project with Spring Boot support. So the springboot-example is implemented manually.
