### ISSUE TITLE
Templates: JPA 2.1 @ForeignKey

### ISSUE THREAD

**Issue by deafff** [sculptor/sculptor#168]
3.1.0-SNAPSHOT is still using Hibernate `@ForeignKey` which was [deprecated after v4.3.0](https://hibernate.atlassian.net/browse/HHH-8170). I'm now getting lots of warnings and JPA validation errors (foreign keys missing in the table).

```
import org.hibernate.annotations.ForeignKey;
```

should be changed to

```
import javax.persistence.ForeignKey;
```

and annotations like 

```
@JoinColumn(name = "COUNTRY_ID", nullable = false)
@ForeignKey(name = "FK_CITY_COUNTRY_ID")
```

to JPA 2.1 compliant

```
@JoinColumn(name = "COUNTRY_ID", nullable = false, foreignKey=@ForeignKey(name="FK_CITY_COUNTRY_ID"))
```

**Comment by tjuerge** [comment]
This is missing from #139.

**Comment by tjuerge** [comment]
Using the JPA annotation `@ForeignKey` means we have to support different JPA versions (again) in Sculptor (depending on the JPA provider):
* JPA 2.1 for Hibernate, Eclipse Link and DataNucleus
* JPA 2.0 for OpenJPA and Google AppEngine (via DataNucleus plugin)

So we have to set the JPA version in `persistence.xml` in accordance to the JPA provider.

**Comment by tjuerge** [comment]
It seems that the JPA 2.1 annotation `@ForeignKey`doesn't work in Hibernate 4.3.x fully:
* [HHH-8862 - Setting foreign key name on @CollectionTable has no effect](https://hibernate.atlassian.net/browse/HHH-8862)
* [Stackoverflow - The ForeignKey jpa/hibernate annotation does not work as exptected](http://stackoverflow.com/questions/28083000/the-foreignkey-jpa-hibernate-annotation-does-not-work-as-exptected?lq=1)

**Comment by tjuerge** [comment]
With Hibernate 6 the deprecated annotation will be removed ([HHH-8969](https://hibernate.atlassian.net/browse/HHH-8969)).

**Comment by matt-hao** [comment]
hello tjuerge , i'm a freshman to learn jpa. i have also meet this problem, can u tell me how to solve this ?

**Comment by tavoda** [comment]
Because a lot changes in Hibernate 5.2 which are preparation steps for 6 we have to make at least Enum template to recognize Hibernate > 5.2 I will try to improve generation of foreign key when 5.2 is specified. First idea is to use option `jpa.provider=hibernate52`.

**Comment by Ysosa** [comment]
to JPA 2.1 compliant

@JoinColumn(name = "COUNTRY_ID", nullable = false, foreignKey=@ForeignKey(name="FK_CITY_COUNTRY_ID"))

Its work fine!! thank u
