### ISSUE TITLE
Generics in traits

### ISSUE THREAD

**Issue by deafff** [sculptor/sculptor#169]
I'm trying to create a trait with a generics:
```
Trait Links {
    def java.util.concurrent.ConcurrentMap<String, String> getLinks();
}
```
Eclipse plugin (both 3.0.6 and today's 3.1.0-snapshot) shows errors like these:
```
'String' is a reserved keyword which is not allowed as Identifier. Please choose another word or alternatively escape it with the caret (^) character, e.g. '^String'
```

**Comment by tjuerge** [comment]
You hit a general limitation of Sculptors DSL: [It doesn't support generics fully](https://github.com/sculptor/sculptor/blob/develop/sculptor-eclipse/org.sculptor.dsl/src/org/sculptor/dsl/Sculptordsl.xtext#L173).

You can try to workaround this issue by defining your own DSL type (with the corresponding mapping to a Java type) as described [here](http://sculptorgenerator.org/documentation/developers-guide#types).

**Comment by deafff** [comment]
Ok, also in this case, it was enough for me to define it as:
```
Trait Links {
    def Map<String, String> getLinks();
}
```
as Map and other collections are already mapped to Java types.
