### ISSUE TITLE
The imported btdesing file could not be found when trying the "Cross Project" feature

### ISSUE THREAD

**Issue by zhongweijun** [sculptor/sculptor#172]
Environment: 
JDK: "1.7.0_40-ea"
Maven: 3.1.1
Eclipse: eclipse-dsl-luna-SR2-win32-x86_64 with Xtext SDK 2.8.0 pre-installed.
Sculptor: 3.0.6

I tryed the "Cross Project" feature example which is mentioned in the "Advanced Tutorial". 

1. I created a "org.foo.common" project, and defined 2 btdesign files. The org.foo.common project could be compiled successfully.
   The content of file "model.btdesign":
   ~~~
   import "classpath:/model-sharedtypes.btdesign"

   Application FooCommon {
       basePackage = org.foo.common
   }
   ~~~

   The content of file "model-sharedtypes.btdesign"
   ~~~
   ApplicationPart CommonPart {
 
       Module sharedtypes {
           basePackage=org.foo.common.sharedtypes
 
           BasicType Money {
               String currency;
               BigDecimal amount;
           }
       }
   }
   ~~~

2. I created the other "org.bank" project, and defined its btdesign which is imported model-sharedtypes.btdesign. And, I included the org.foo.common project with client classifier as well, the Xtext editor doesn't report any error.
   The content of model.btdesign:
   ~~~
   import "classpath:/model-sharedtypes.btdesign"

   Application Bank {
       basePackage = org.bank

       Module accounting {
           Entity Account {
               String accountNumber key;
               - @Money balance;
           }
       }
   }
   ~~~

But when I was trying to compile the "org.bank" project with maven install, an error was thrown by maven. Below is the detailed info:
~~~
[ERROR] Failed to execute goal org.sculptorgenerator:sculptor-maven-plugin:3.0.6:generate (code-generation) on project org.bank: Execution code-generation of goal org.sculptorgenerator:sculptor-maven-plugin:3.0.6:generate failed: org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on classpath. URI was 'classpath:/model-sharedtypes.btdesign' -> [Help 1]
[ERROR] 
~~~
It seems that the imported ".btdesign" file could not be found by Xtext. What's the problem? Is it an issue of migrating to Xtext 2.8.0?

**Comment by zhongweijun** [comment]
Update my assumptioin:
I think it's not a issue related to Xtext 2.8.0, because the sculptor v3.0.6 is using Xtext 2.6.2.

**Comment by tjuerge** [comment]
Sculptors cross-project feature is based on Mavens classpath dependency resolution:

The imported "model-sharedtypes.btdesign" has to be packaged (together with the corresponding model implementation classes) in the root folder of the JAR created from the "org.foo.common" project.
The importing "org.bank" project has to add the "org.foo.common" project (with the aforementioned model definition and implementation) to the list of its dependencies.

In the Eclipses project navigator view check the importing "org.bank" projects "Maven Dependencies" if here the imported  "org.foo.common" projects JAR is listed. Uncollapse the JARs node and check if the model.btdesign is listed as well.

**Comment by tjuerge** [comment]
And make sure that in the imported projects POM the client JAR is created properly via the Maven JAR plugin:
~~~
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<executions>
		<execution>
			<id>${project.artifactId}-client</id>
			<goals>
				<goal>jar</goal>
			</goals>
			<phase>package</phase>
				<configuration>
					<classifier>client</classifier>
					<includes>
						<include>**/serviceapi/*.class</include>
						<include>**/domain/*.class</include>
						<include>**/exception/*.class</include>
						<include>**/*.btdesign</include>
						<include>**/sculptor-generator.properties</include>
					</includes>
				</configuration>
			</execution>
		</executions>
	</plugin>
</plugins>
~~~

**Comment by zhongweijun** [comment]
Yes dear tjuerge, I checked packaged file of "org.foo.common-1.0-SNAPSHOT-client.jar", both its model.btdesign and model-sharedtypes.btdesign were packaged in.
And, the eclipse xtext dsl editor doesn't report "Imported resource could not be found" error, so I think the Eclipses project navigator has found the file.

The problem happens when I was trying to compile or do the generate-sources for the "org.bank" project...

**Comment by tjuerge** [comment]
>And, the eclipse xtext dsl editor doesn't report "Imported resource could not be found" error, so I think the Eclipses project navigator has found the file.

Dependency resolution in Eclipse and Maven are different beasts: Within Eclipse the Xtext plugin is maintaing a global index of all Xtext resources defined in Xtext-enabled projects visible in the Eclipse workspace (see "Global Scopes Based On External Configuration (e.g. Class Path Based)" in [chapter "Scoping" of Xtext doc](http://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping)). In Maven Javas plain Classloader resource API is used (via Xtexts implementation of an EMF [ResourceSet](https://github.com/eclipse/emf/blob/R2_9_0/plugins/org.eclipse.emf.ecore/src/org/eclipse/emf/ecore/resource/ResourceSet.java)).

In Sculptors Maven plugin this [XtextResourceSet](https://github.com/eclipse/xtext/blob/v2.8.0/plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResourceSet.java) is used to [resolve imported models](https://github.com/sculptor/sculptor/blob/develop/sculptor-generator/sculptor-generator-core/src/main/java/org/sculptor/generator/workflow/SculptorGeneratorWorkflow.xtend#L113).

Right now I have no clue about the reason for this issue in your specific context. Maybe the stacktrace of the issue in the Maven build helps. So please add a comment with the stacktrace created via  `mvn clean install -e`.

The output of `mvn dependency:tree` may help as well. And add the output of Sculptors Maven plugin in verbose mode (`<verbose>true</verbose>`).

**Comment by zhongweijun** [comment]
E:\src-sculptor-demo\org.bank>mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building New Sculptor Project :: Business Tier 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ org.bank ---
[INFO] org.bank:org.bank:jar:1.0-SNAPSHOT
[INFO] +- org.sculptorgenerator:sculptor-framework-main:jar:without-ejb:3.0.6:compile
[INFO] +- org.hibernate:hibernate-validator:jar:5.0.3.Final:compile
[INFO] |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.1.1.GA:compile
[INFO] |  \- com.fasterxml:classmate:jar:1.0.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.7:compile
[INFO] +- org.slf4j:log4j-over-slf4j:jar:1.7.7:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.2:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] +- javax.transaction:jta:jar:1.1:compile
[INFO] +- org.springframework:spring-context:jar:3.2.10.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:3.2.10.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:3.2.10.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:3.2.10.RELEASE:compile
[INFO] +- org.springframework:spring-aop:jar:3.2.10.RELEASE:compile
[INFO] |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] +- org.springframework:spring-orm:jar:3.2.10.RELEASE:compile
[INFO] +- org.springframework:spring-jdbc:jar:3.2.10.RELEASE:compile
[INFO] +- org.springframework:spring-tx:jar:3.2.10.RELEASE:compile
[INFO] +- org.springframework:spring-context-support:jar:3.2.10.RELEASE:compile
[INFO] +- commons-pool:commons-pool:jar:1.6:compile
[INFO] +- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- commons-beanutils:commons-beanutils:jar:1.8.3:compile
[INFO] +- joda-time:joda-time:jar:2.2:compile
[INFO] +- org.aspectj:aspectjweaver:jar:1.7.4:compile
[INFO] +- org.aspectj:aspectjrt:jar:1.7.4:compile
[INFO] +- org.sculptorgenerator:sculptor-framework-test:jar:3.0.6:test
[INFO] |  \- org.sculptorgenerator:sculptor-framework-main:jar:3.0.6:test
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.dbunit:dbunit:jar:2.4.9:test
[INFO] |  \- commons-collections:commons-collections:jar:3.2.1:test
[INFO] +- org.springframework:spring-test:jar:3.2.10.RELEASE:test
[INFO] +- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] +- org.hsqldb:hsqldb:jar:2.3.2:compile
[INFO] +- org.foo:org.foo.common:jar:client:1.0-SNAPSHOT:compile
[INFO] +- org.hibernate:hibernate-entitymanager:jar:4.2.15.Final:compile
[INFO] |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  +- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar:1.0.1.Final:compile
[INFO] |  +- org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.1.Final:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:4.0.2.Final:compile
[INFO] |  \- org.hibernate:hibernate-core:jar:4.2.15.Final:compile
[INFO] |     \- antlr:antlr:jar:2.7.7:compile
[INFO] +- org.hibernate:hibernate-ehcache:jar:4.2.15.Final:compile
[INFO] |  \- net.sf.ehcache:ehcache-core:jar:2.4.3:compile
[INFO] \- org.jadira.usertype:usertype.core:jar:3.0.0.GA:compile
[INFO]    \- org.jadira.usertype:usertype.spi:jar:3.0.0.GA:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.815s
[INFO] Finished at: Fri Mar 20 08:17:14 CST 2015
[INFO] Final Memory: 13M/221M
[INFO] ------------------------------------------------------------------------

*******************************************************************************************************************************

E:\src-sculptor-demo\org.bank>mvn clean install -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building New Sculptor Project :: Business Tier 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.bank ---
[INFO] Deleting E:\src-sculptor-demo\org.bank\target
[INFO]
[INFO] --- sculptor-maven-plugin:3.0.6:clean (cleanup) @ org.bank ---
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\generated\java
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\generated\resources
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\test\generated\java
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\test\generated\resources
[INFO]
[INFO] --- sculptor-maven-plugin:3.0.6:generate (code-generation) @ org.bank ---
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\generated\java
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\generated\resources
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\test\generated\java
[INFO] Deleting previously generated files in directory: E:\src-sculptor-demo\org.bank\src\test\generated\resources
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.546s
[INFO] Finished at: Fri Mar 20 08:22:05 CST 2015
[INFO] Final Memory: 23M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sculptorgenerator:sculptor-maven-plugin:3.0.6:generate (code-generation) on project org.bank: Execution code-generation of go
al org.sculptorgenerator:sculptor-maven-plugin:3.0.6:generate failed: org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on cla
sspath. URI was 'classpath:/model-sharedtypes.btdesign' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sculptorgenerator:sculptor-maven-plugin:3.0.6:generate (code-generation) on p
roject org.bank: Execution code-generation of goal org.sculptorgenerator:sculptor-maven-plugin:3.0.6:generate failed: org.eclipse.xtext.resource.FileNotFoundOnC
lasspathException: Couldn't find resource on classpath. URI was 'classpath:/model-sharedtypes.btdesign'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution code-generation of goal org.sculptorgenerator:sculptor-maven-plugin:3.0.6:generate failed
: org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on classpath. URI was 'classpath:/model-sharedtypes.btdesign'
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.eclipse.xtext.resource.ClasspathUriResolutionException: org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on cl
asspath. URI was 'classpath:/model-sharedtypes.btdesign'
        at org.eclipse.xtext.resource.ClassloaderClasspathUriResolver.resolve(ClassloaderClasspathUriResolver.java:48)
        at org.eclipse.xtext.resource.XtextResourceSet.resolveClasspathURI(XtextResourceSet.java:160)
        at org.eclipse.xtext.resource.XtextResourceSet.access$0(XtextResourceSet.java:159)
        at org.eclipse.xtext.resource.XtextResourceSet$1.normalize(XtextResourceSet.java:216)
        at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:178)
        at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:24)
        at org.sculptor.generator.workflow.SculptorGeneratorWorkflow.readModel(SculptorGeneratorWorkflow.java:181)
        at org.sculptor.generator.workflow.SculptorGeneratorWorkflow.run(SculptorGeneratorWorkflow.java:106)
        at org.sculptor.generator.SculptorGeneratorRunner.run(SculptorGeneratorRunner.java:50)
        at org.sculptor.maven.plugin.GeneratorMojo.doRunGenerator(GeneratorMojo.java:474)
        at org.sculptor.maven.plugin.GeneratorMojo.executeGenerator(GeneratorMojo.java:439)
        at org.sculptor.maven.plugin.GeneratorMojo.execute(GeneratorMojo.java:223)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        ... 20 more
Caused by: org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on classpath. URI was 'classpath:/model-sharedtypes.btdesign'
        at org.eclipse.xtext.resource.ClassloaderClasspathUriResolver.findResourceOnClasspath(ClassloaderClasspathUriResolver.java:60)
        at org.eclipse.xtext.resource.ClassloaderClasspathUriResolver.resolve(ClassloaderClasspathUriResolver.java:45)
        ... 32 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by zhongweijun** [comment]
In above example, the project of "org.foo:org.foo.common:jar:client:1.0-SNAPSHOT:compile" has the sharedtypes btdesign.

Dear tjuerge, or would you please add a cross project example to the code base for our users' reference? Thank you. :-)

**Comment by tjuerge** [comment]
> Dear tjuerge, or would you please add a cross project example to the code base for our users' reference? Thank you. :-)

Yes, I was thinking about this as well :-)
It seems that we need this kind of example as an additional test case.

**Comment by tjuerge** [comment]
From the attached log it seems that you're running Sculptor on Windows on drive E:. Is there anything special to this drive E:? In the forum [someone reported issues on Windows with a truecrypt drive](https://groups.google.com/d/msg/sculptorgenerator/J4Dqveh4Nxc/I_SqFkgpJCsJ).

Any chance to test Sculptor on plain vanilla drive C:? Or better use Sculptor on a *nix OS :-P

**Comment by zhongweijun** [comment]
No, there's nothing special to drive e:. And I moved the projects to drive c:, but it doesn't help.
I will try to check if it works in *nix OS, but you know, windows is one of the most popular development environment too. :-)

**Comment by zhongweijun** [comment]
I debugged into the "readModel" method in SculptorGeneratorWorkflow class. It was the XtextResourceSet.getResource("classpath:/model-sharedtypes.btdesign", true) method which throws the exception when the file "model-sharedtypes.btdesign" was in another jar files.
I think it is cause by the uncorrect classpath settings for the XtextResourceSet.

And I checked the develop branch of source code, I found the SculptorGeneratorRunner has changed to use ContextClassLoaderAwareRuntimeResourceSetInitializer instead. So I think the problem will be solved in release 3.1.0.

Dear tjuerge, would you please help me to check this issue? I'm really not familiar with the Xtext source codes.

**Comment by zhongweijun** [comment]
The test on release 3.1.0-SNAPSHOT is failed too.

**Comment by zhongweijun** [comment]
It seems that we should add the org.foo.common dependency to the sculptor-maven-plugin.
And it solved the problem.

```
	<build>
		<plugins>
			<plugin>
				<groupId>org.sculptorgenerator</groupId>
				<artifactId>sculptor-maven-plugin</artifactId>
				<version>${sculptor-version}</version>
				<configuration>
					<verbose>true</verbose>
				</configuration>
				<executions>
					<execution>
						<id>cleanup</id>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
					<execution>
						<id>code-generation</id>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
					<execution>
						<id>image-generation</id>
						<goals>
							<goal>generate-images</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.foo</groupId>
						<artifactId>org.foo.common</artifactId>
						<version>1.0-SNAPSHOT</version>
						<classifier>client</classifier>
					</dependency>
				</dependencies>
			</plugin>
```

**Comment by tjuerge** [comment]
>It seems that we should add the org.foo.common dependency to the sculptor-maven-plugin.
And it solved the problem.

I'm glad you found the solution.

You're right, the `org.foo.common` dependency must be added as dependency to the Sculptor Maven plugin. I've updated the [corresponding chapter in the Advanced Tutorial](http://sculptorgenerator.org/documentation/advanced-tutorial#cross-project-references) and added a [new chapter in the Maven plugin documentation](http://sculptorgenerator.org/documentation/maven-plugin#classpath).

Thanks for spotting this.
