### ISSUE TITLE
Templates: UniqueConstraint for ValueObject key attributes should be optional.

### ISSUE THREAD

**Issue by zhongweijun** [sculptor/sculptor#177]
As described in the document of "advanced-tutorial", the "key" keywords placed on Entity attributes and  ValueObject (BasicType) attributes have different meaning.

The key attributes of an entity, are used for identify the object (the id is just a surrogate attribute if it's not set as a key) in business. And, the key attributes of a ValueObject, are primary used to determine if two valueobjects are equal.

Based on above two basic concepts,  the key attributes of entities should apparently be constrainted to be unique, but the key attributes of value-objects are not.

For the database storage of Value Objects, there are two strategies, shareable value-objects and non-share valueobjects. In non-shareable scenario, two entities have their own copy of value-object even though the two value-objects are equal (This case the value-objects are normally modeled as !aggregate, and they are a part of the entity -- should also be orphanRemovel). In shareable scenario, two entities shared same copy of value object if the attributes' value are equal (This case is mostly suitable for the value objects which represents some industry-defined/standard/code values). From my experience, the former strategy is more common, and the after strategy should be assisted with a management service (for standard values) and a factory service (for object constructing).

Both above strategies should be alternative for developers. The key-point is, we doesn't changing the meaning of equal for two objects.

**Comment by tavoda** [comment]
If it's not unique than it is not key. What is difference between having key and use it as shareable object and not having key at all?
If it is only question of equals() method than you can write your own version of equals() in GAP class however be careful, hibernate is using equals() and it can lead to strange errors. I'm not sure what will happen if you will have two different object with two different IDs but equals.
Another problem is hashCode() method if you have to use same entity in Set. I'm not sure we can generate it right way for 'shared' value objects.

**Comment by zhongweijun** [comment]
Hi Tavoda,
Thanks for your reply, but I still have some concerns.
For "two different object with two different IDs but equals" issue, I think this is where the differences are between Entity and ValueObjects in DDD core concept.
In SculptorGenerator DSL, "BasicType" and "ValueObject" are both modeled for the ValueObject concept of DDD. The main difference between them is, "BasicType" is a ValueObject which is stored in the same table as the Domain Object referencing it, but the "ValueObject" is stored in a separate table. 
Whether storing a ValueObject in same table or a separated table is an inner design of module, we may change the technical decision as time goes on. 
Here we can assume an example (May not suitable for "small" value objects as Money, but possible for "large" objects).
At the beginning, we modeled Money as a BasicType:
Entity Product {
    - @Money money;
}
BasicType Money {
      ... ...
}
As time goes on, we may decide to store the money to a separated table:
ValueObject Money {
      ... ...
}
According to the principle of encapsulation, we want to limit the effect not spreading to the client(or consumer of the module), where it may estimate if "productA.money == productB.money".

As you have said, hibernate is using equals() and it can lead to strange errors (caused by the ORM mapping mechanism for @Entity in ORM framework? I'm not sure. The difference concepts of the same word "Entity" in DDD domain and ORM domain are confusing). 

Dear Tavoda, So do you think if it's useful to add an additional method (e.g. sameValueOf) besides the default equals() method?

**Comment by zhongweijun** [comment]
Though "BasicType" and "ValueObject" are both mapping to ValueObject for DDD domain, but the "key" keywords placed on their attributes have different effect, it may cause user's confusion. This is my main concern.
You placed a "key" keyword on a BasicType's attribute, the attribute is measured for equation of two objects. You placed the same keyword on a ValueObject's attribute, it is not used for measuring the equation of two objects, but is used for identify a "unique" object (which is the chief character of an "Entity" in DDD, but not a ValueObject). Some day if you decide to change a "BasicType"(same table storage) To a "ValueObject"(separated table storage), you have to take care of the differences (Not kind to the tool's user).
I understand the main difference of a "ValueObject" and an "Entity" here in SculptorGenerator is the default behavior of if it's changeable, but I think it's not enough. It loses the key character of a "ValueObject", which it can be copied and cloned. Though two ValueObjects are stored as two records, if their key attributes are equal, they are equal. It's not only your inner design, but also a contract to your module's calling client.

**Comment by tjuerge** [comment]
> As described in the document of "advanced-tutorial", the "key" keywords placed on Entity attributes and ValueObject (BasicType) attributes have different meaning.
> 
> The key attributes of an entity, are used for identify the object (the id is just a surrogate attribute if it's not set as a key) in business. And, the key attributes of a ValueObject, are primary used to determine if two valueobjects are equal.

From my understanding [Sculptors keyword `key`](http://sculptorgenerator.org/documentation/advanced-tutorial#key) is about object equality of domain objects (Entity, ValueObject and BasicType) and used for generating the `getKey()` method referenced in the frameworks `equals()` and `hashCode()` implementation needed for Java collections (as described in the [Hibernate Wiki](https://developer.jboss.org/wiki/EqualsAndHashCode)).

And Sculptors internally generated [id property](http://sculptorgenerator.org/documentation/advanced-tutorial#id) is about object identity of persistent objects (Entities and persistent ValueObjects) and has no business meaning at all (as stated in the chapter "Separating object id and business key" of the [Hibernate Wiki](https://developer.jboss.org/wiki/EqualsAndHashCode)).

**Comment by zhongweijun** [comment]
Thanks Tjuerge, your explaination is quite clear. :-)
Now let's come back to the original question.
The "UniqueConstraint" is a storage (table) level issue, but the equals() and hashCode() is a Java collection level issue of Hibernate framework. In another word, we should keep a ValueObject "unique" in a java collection (which normally delegate an Entity's attribute), but maybe it's not need to constraint a ValueObject to be "unique" in a storage table.

**Comment by tjuerge** [comment]
With my explanation I was trying to make the point that Sculptors keyword `key` is about generating code for object equality check needed for Java collections and ORMs. As Pavel said if attributes are marked as key then they have to be unique or they are not usable as key.

If the attributes are not unique then don't use the keyword `key`. In this case an internally generated UUID will by used as key instead.

**Comment by zhongweijun** [comment]
That's the point.
"BasicType" and "ValueObject" are both ValueObjects. We're using the keyword "key" for BasicType for evaluating if two objects are equal. But we're using the keyword "key" for ValueObject for defining if the attribute are unique in a table. As I've mentioned before, I think it's somewhat bad smell.

**Comment by tjuerge** [comment]
> "BasicType" and "ValueObject" are both ValueObjects. We're using the keyword "key" for BasicType for evaluating if two objects are equal. But we're using the keyword "key" for ValueObject for defining if the attribute are unique in a table.

From my understanding is the unique column constraint used for the key attribute(s) of all persistent domain objects (including BasicType) regardless of its type, e.g. in [DomainObjectAttributeAnnotationTmpl.columnAnnotations()](https://github.com/sculptor/sculptor/blob/develop/sculptor-generator/sculptor-generator-templates/src/main/java/org/sculptor/generator/template/domain/DomainObjectAttributeAnnotationTmpl.xtend#L167) is no special check for BasicType.

**Comment by tavoda** [comment]
If we want to implement some other way for creating indexes or with some 'correct' way how to handle equals() and hashCode() for hibernate we can create new issue.
