### ISSUE TITLE
Templates: DSL Keyword "orderColumn" not recognised for references of type "List"

### ISSUE THREAD

**Issue by tjuerge** [sculptor/sculptor#178]
In a [forum post](https://groups.google.com/d/msg/sculptorgenerator/9Xk7fVvk3FI/PqlWnALmiCgJ) was reported that despite of using DSL keyword `orderColumn` for a `List`reference the corresponding JPA annotation `@javax.persistence.OrderColumn` wasn't generated.

**Comment by tjuerge** [comment]
It seems that the extension method `HelperBase.getCollectionType()` isn't called in the corresponding template `DomainObjectReferenceAnnotationTmpl`because the meta model class `Reference` has a method with the same name (the getter for the attribute `collectiontype`).

So we have to use here the method call `getCollectionType(ref)`instead of `ref.collectionType`.

**Comment by tjuerge** [comment]
The same is with the extension method `DbHelperbase.isInverse()`. This is in't used as well due to the existing method `Reference.isInverse()`.

So we have to use here the method call `isInverse(ref)`instead of `ref.inverse`.

**Comment by tavoda** [comment]
Methods in helper classes renamed to avoid confusion. In templates on places where necessary I used new method. It's used also in OracleDDL and MySQLDDL templates but I don't see reason to call it there then original methods from Reference are called.
