### ISSUE TITLE
Sculptor not working with parent pom

### ISSUE THREAD

**Issue by RichardWalshTZ** [sculptor/sculptor#185]
We were using a flat project structure with 2 projects 

Each project had some sculptor btdesign files.

Each project had its own POM and sculptorgenerator

main/
        /module1
                     pom.xml
        /module2
                     pom.xml

I then needed to add a parent POM. Which I did and it referenced the 2 child projects as <modules>...

main/
        pom.xml [parent]
        /module1
                     pom.xml [child]
        /module2
                     pom.xml [child]

However when I did this the sculptor generator started generating the code into the main directory.

main/src/generated/java/...

Instead of under the module1 directory...

No idea why. Any ideas?

**Comment by tavoda** [comment]
We are using following layout which works:
In parent POM we define in pluginManagement section configuration like:
```
	<build>
		<pluginManagement>
			<plugins>
			<plugin>
				<groupId>org.sculptorgenerator</groupId>
				<artifactId>sculptor-maven-plugin</artifactId>
				<version>${sculptor.version}</version>
				<executions>
					<execution>
						<id>cleanup</id>
						<goals><goal>clean</goal></goals>
					</execution>
					<execution>
						<id>code-generation</id>
						<goals><goal>generate</goal></goals>
					</execution>
				</executions>
				<configuration>
					<verbose>true</verbose>
				</configuration>
			</plugin>
```
And then in each module just use it:
```
			<plugin>
				<groupId>org.sculptorgenerator</groupId>
				<artifactId>sculptor-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>eu.f4s.projA</groupId>
						<artifactId>projA-service-gen</artifactId>
						<version>${projA.version}</version>
					</dependency>
				</dependencies>
			</plugin>
```
We even share same 'projA-service-gen' between projects but you can have special for each project.
