### ISSUE TITLE
Framework: Repository Hint with OrderBy doesn't work

### ISSUE THREAD

**Issue by steferik** [sculptor/sculptor#188]
If a repository specifies a hint that states a orderBy definition it will never be used.
The problem is that the new query is assembled into a local variable instead of the correct class variable.

See JpaFindAllAccessImplGeneric.prepareOrderBy() line 85:
Change: 
`query +=`

To:
`this.query +=`

**Comment by tjuerge** [comment]
You're right, in [`JpaFindAllAccessImplGeneric.prepareOrderBy()`](https://github.com/sculptor/sculptor/blob/1c795de176109ed272fd8d224b3bfdc37f0d85d7/sculptor-framework/sculptor-framework-main/src/main/java/org/sculptor/framework/accessimpl/jpa/JpaFindAllAccessImplGeneric.java#L85) the statement `setQuery(query)` is missing.

Thanks for spotting this.
