### ISSUE TITLE
scope error

### ISSUE THREAD

**Issue by magick93** [sculptor/sculptor#194]
When I try the advanced example dsl I get the following validation errors in Eclipse, and therefore it does not generate any code.

![screenshot from 2018-06-03 02-32-11](https://user-images.githubusercontent.com/2173213/40877521-8cac969a-66d6-11e8-9adb-6a886237647b.png)

Xtext Version
------------------

Xtext Complete SDK	2.12.0.v20170519-1412	org.eclipse.xtext.sdk.feature.group	Eclipse Xtext

**Comment by tavoda** [comment]
Can please somebody test this after all framework updates?

**Comment by tjuerge** [comment]
Please keep in mind that the [Eclipse plugin](http://sculptorgenerator.org/documentation/eclipse-plugin) is only used for grammar validation. Here make sure that the [corresponding requirements](http://sculptorgenerator.org/documentation/eclipse-plugin#caveats) (project nature and automatic build) are met.

The code generation happens in the [Maven plugin](http://sculptorgenerator.org/documentation/maven-plugin).
