### ISSUE TITLE
Dependency issue with DDD sample

### ISSUE THREAD

**Issue by garrettbates** [sculptor/sculptor#223]
**Context**

Following this tutorial: http://sculptorgenerator.org/documentation/ddd-sample

Downloaded this source code: http://sculptorgenerator.org/images/documentation/ddd-sample/Sculptor-DDDSample-src.zip

Ran mvn and immediately ran into dependency issues.

**Steps to reproduce**

* Download zip
* Run the following command:

```
mvn clean install -U
```

**Error**

<img width="1478" alt="Screen Shot 2020-03-19 at 3 17 44 AM" src="https://user-images.githubusercontent.com/7095829/77056813-3e522780-6990-11ea-9d45-195f0709d590.png">

**Comment by tjuerge** [comment]
The source code available from the web site is outdated and removed now. The tutorial is updated accordingly.

Please use the corresponding source code from Sculptor's examples and keep in mind that Sculptor currently only supports Java 8 #225.
