### ISSUE TITLE
Build failure within sculptor repo itself

### ISSUE THREAD

**Issue by garrettbates** [sculptor/sculptor#224]
**Context**

Thought perhaps code base maintained within sculptor repo would be most up-to-date with potential fixes within the examples.

Ran ./mvnw clean install but immediately ran into compile time issues.

Maven Version: 3.6.3
Java Version: 13.0.2

**Steps to reproduce**

* Clone this repo:

```
https://github.com/sculptor/sculptor.git
```

* Run the following command

```
./mvnw clean install
```
**Error message**

<img width="1479" alt="Screen Shot 2020-03-19 at 4 05 45 AM" src="https://user-images.githubusercontent.com/7095829/77061386-62653700-6997-11ea-89d1-25dde96e4518.png">

**Comment by tjuerge** [comment]
Sculptor currently only supports Java 8 #225.
