### ISSUE TITLE
Add support for Java 11

### ISSUE THREAD

**Issue by tjuerge** [sculptor/sculptor#225]
Currently Sculptor only supports Java 8 (the previous LTS version). We should add support for Java 11 (the current LTS version).

Some things to keep in mind:
* removal of EE APIs, e.g. `javax.annotation.*`

**Comment by tjuerge** [comment]
@tavoda Any chance to look into the issues with Hibernate under Java 11? Our examples are not working with the current dependencies.

**Comment by tavoda** [comment]
Of course, Java 11+ and library update are primary concerns for this update.

**Comment by tjuerge** [comment]
> Of course, Java 11+ and library update are primary concerns for this update.

Cool, the main project seems to work (it compiles and no test fails). But the dependencies need some changes, e.g. all libraries which are using bytecode manipulation (via asm or javassist) have to be checked.

**Comment by tavoda** [comment]
I'm already using it for some internal projects with Java 11. However we have our own project templates. I have to check where are conflicts or missing version updates.

**Comment by tavoda** [comment]
Except one test (ejb-example) it's working with Java 11.

**Comment by tjuerge** [comment]
> Except one test (ejb-example) it's working with Java 11.

You're right, the example with the OpenEJB testing stuff is the only which isn't working. I've to check...

**Comment by tavoda** [comment]
I tracked difference down to org.apache.xbean.finder.ClassLoaders.findUrls(....) method. There is test for URLClassLoader:
            if (URLClassLoader.class.isInstance(classLoader) && !DONT_USE_GET_URLS)
Java 11 is not using URLClassLoader, therefore it goes different path and don't include helloworl/target/classes to list of URLs.
Under Java 8 it runs fine. Maybe we can dissable this test for java 11.

**Comment by tavoda** [comment]
ejb-example is removed from build for now (commented out in pom.xml of sculptor-example project)

**Comment by tavoda** [comment]
Project is compiled with Java 8. Java 11 is supported very well. Future version will be compiled directly by Java 11.
