### ISSUE TITLE
Using Plan Text Editor

### ISSUE THREAD

**Issue by fastcode-inc** [sculptor/sculptor#228]
Hi,

The project looks awesome!

How do I use a plain text editor with this project for creating the DSL and then use the Maven Plugin to generate the code?  I am asking because I don't use Eclipse - I use IntelliJ.

Thank you for any information.

**Comment by tjuerge** [comment]
As [mentioned in the installation guide](http://sculptorgenerator.org/documentation/installation#eclipse) you can use any text editor to manipulate Sculptor's DSL files (`*.btdesign`). But with [Sculptor's Eclipse plugin](http://sculptorgenerator.org/documentation/eclipse-plugin) you get  error highlight, code completion, and outline.

So in your case read "Sculptor DSL editor" as "IntelliJ IDEA" while browsing through Sculptor's documentation (e.g. [this one](http://sculptorgenerator.org/documentation/hello-world-tutorial#part-2---generate-code)) :-)

**Comment by fastcode-inc** [comment]
Thank you very much for your response.

It looks like XText supports editors beyond Eclipse as noted here (
https://www.eclipse.org/Xtext/index.html#platform-comparison and
https://www.eclipse.org/Xtext/documentation/330_web_support.html  ).  Does
this mean that I can use IntelliJ (supports Language Server Protocol) or
one of the supported browser-based editors also?

Sunil
