### ISSUE TITLE
Add option to set output encoding

### ISSUE THREAD

**Issue by MathiasAugstein** [sculptor/sculptor#245]
The default output encoding of sculptor is ISO 8859-1, which is not convenient for every use case (for example, we want to use UTF-8). It would be appreciated if you could add an option to set the output encoding. 

Furthermore a better documentation of the default encoding would be nice. I found it out by chance, and the only place which minds the default encoding is [here](http://sculptorgenerator.org/documentation/development-environment#eclipse-text-file-encoding).

**Comment by tavoda** [comment]
Hello @MathiasAugstein, this are limitations of Xtext template engine which is using very 'non standard' template brackets.
