### ISSUE TITLE
Add limited support for generating xtend files from Sculptor

### ISSUE THREAD

**Issue by rcodesmith** [sculptor/sculptor#43]
I'm using XTend for services and repositories in a Sculptor-based project.
The problem is that if I implement a Sculptor service in XTend, Sculptor generators would still generate the .java version, ending up with duplicate classes.

This issue is to add limited support for XTend classes in user projects based on Sculptor.

The first step is to modify Helper.xtend and some key generators to use a .xtend extension if the class is to be generated as an xtend class rather than java.

The templates would still generate Java code rather than XTend code, so it won't compile, but at least it's easy to manually fix, and only needs to be done once per class.

**Comment by tavoda** [comment]
Is this requirement/enhancement still valid?

**Comment by tjuerge** [comment]
IMHO this enhancement is still needed for Xtend-based user projects using Sculptor. Because Sculptor is generating Java code these projects will end up with a mix of Java classes generated by Sculptor and the Xtend compiler (from user-provided Xtend classes).

**Comment by tavoda** [comment]
Iit's integrated in Helper.xtend. I was asking about some other enhancements which can help.
