### ISSUE TITLE
"Unsupported major.minor version 51.0" exception was thrown while compiling with java 1.6.0

### ISSUE THREAD

**Issue by zhongweijun** [sculptor/sculptor#69]
"Unsupported major.minor version 51.0" exception was thrown while compiling with java 1.6.0, But it described in sculptorgenerator's documentation that Java6 is supported.

**Comment by rohitkhadse** [comment]
change java version from 6 to 7/8 in property section of pom.xml
` <java.version>1.8</java.version>`
